# Generated by Django 5.0 on 2023-12-29 02:20

import django.db.models.deletion
import stdimage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Date_Created', models.DateField()),
                ('country_flag', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='countries_flags/', variations={'thumbnail': {'crop': True, 'height': 100, 'width': 100}})),
            ],
            options={
                'verbose_name': 'Countries',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='display_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_new_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_notification_seen',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_country_code',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher')], default=1, help_text='دور المستخدم', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.countries'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('student_name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=50)),
                ('mobile_phone_number', models.CharField(max_length=15)),
                ('parents', models.ManyToManyField(limit_choices_to={'role': 'parent'}, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Parent_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Parent_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='student', to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_id', models.CharField(max_length=20, unique=True)),
                ('role_teacher', models.CharField(blank=True, max_length=50)),
                ('designation_faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_of_contract', models.CharField(blank=True, max_length=50, null=True)),
                ('work_shift', models.CharField(blank=True, max_length=50, null=True)),
                ('work_location', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateField(null=True)),
                ('barcode', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
