# Generated by Django 5.0 on 2023-12-29 03:45

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_countries_rename_display_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='Date_Created',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_flag',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='countries_flags/', variations={'thumbnail': {'crop': True, 'height': 1000, 'width': 1000}}),
        ),
    ]
