# Generated by Django 5.0 on 2023-12-29 16:06

import django.db.models.deletion
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_date_created_countries_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Educational_qualification', models.CharField(blank=True, help_text='المؤهل العلمي', max_length=50, null=True)),
                ('Graduation_Year', models.DateField(blank=True, help_text=' سنة التخرج ', max_length=50, null=True)),
                ('The_university_issued_the_qualification', models.CharField(blank=True, help_text='الجامعة الصادر منها المؤهل', max_length=50, null=True)),
                ('Nationality', models.CharField(blank=True, help_text='الجنسية', max_length=50, null=True)),
                ('Place_of_residence', models.CharField(blank=True, help_text='مكان الاقامة', max_length=50, null=True)),
                ('Name_of_previous_or_current_workplace', models.CharField(blank=True, help_text=' اسم مكان العمل السابق او مكان العمل الحالى', max_length=50, null=True)),
                ('Specialization', models.CharField(blank=True, help_text=' التخصص', max_length=50, null=True)),
                ('Years_of_Experience', models.CharField(blank=True, help_text='سنوات الخبرة ', max_length=50, null=True)),
                ('Years_of_experience_in_online_education', models.CharField(blank=True, help_text='سنوات الخبرة ف التعليم الاؤنلاين', max_length=50, null=True)),
                ('The_training_courses_you_took', models.CharField(blank=True, help_text=' الدورات الحاصل عليها', max_length=50, null=True)),
                ('Educational_stage', models.CharField(blank=True, choices=[('primary_education', 'Primary education'), ('secondary_education', 'Secondary Education'), ('High_school', 'High school'), ('Technical_education', 'Technical education'), ('University_education', 'University education')], help_text='مراحل التعليم ', max_length=50, null=True)),
                ('Type_of_education', models.CharField(blank=True, choices=[('government_education', 'Government education'), ('arabic_private_education', 'Arabic private education'), ('foreign_private_school', 'foreign privat eschool')], help_text='نوع التعليم', max_length=50, null=True)),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='profile-image/', variations={'thumbnail': {'crop': True, 'height': 1000, 'width': 1000}})),
                ('user', models.ForeignKey(help_text='البروفايل', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileDateProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='ارفع فايل', upload_to='profile-file/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_File', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileDateRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Educational_qualification', models.BooleanField(default=False)),
                ('Graduation_Year', models.BooleanField(default=False)),
                ('The_university_issued_the_qualification', models.BooleanField(default=False)),
                ('Nationality', models.BooleanField(default=False)),
                ('Place_of_residence', models.BooleanField(default=False)),
                ('Name_of_previous_or_current_workplace', models.BooleanField(default=False)),
                ('Specialization', models.BooleanField(default=False)),
                ('Years_of_Experience', models.BooleanField(default=False)),
                ('Years_of_experience_in_online_education', models.BooleanField(default=False)),
                ('The_training_courses_you_took', models.BooleanField(default=False)),
                ('Educational_stage', models.BooleanField(default=False)),
                ('Type_of_education', models.BooleanField(default=False)),
                ('image', models.BooleanField(default=False)),
                ('file', models.BooleanField(default=False)),
                ('user', models.OneToOneField(help_text='البروفايل', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
