# Generated by Django 5.0 on 2023-12-31 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_filedateprofileuser_userprofiledaterequired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='marital_status',
        ),
    ]
