# Generated by Django 5.0 on 2024-01-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_address_remove_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(related_name='student', to='users.student'),
        ),
    ]
