# Generated by Django 5.0 on 2024-01-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_parent_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='children',
        ),
    ]
