# Generated by Django 5.0 on 2024-01-03 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_parent_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
